"use client";

import { useState, useCallback } from "react";
import { TOKENS, resolveTokens, TokenSet } from "@/lib/genreTokens";

// ─── Types ────────────────────────────────────────────────────────

interface MemberInput  { name: string; role: string; }
interface TrackInput   { number: number; title: string; duration: string; }

interface FormData {
  // Step 1 — Identity
  name: string;
  genre: string;
  tagline: string;
  origin: string;
  founded: string;
  // Step 2 — Story
  bio: string[];
  members: MemberInput[];
  awards: string;
  // Step 3 — Links
  spotify: string;
  appleMusic: string;
  youtube: string;
  soundcloud: string;
  bandcamp: string;
  instagram: string;
  tiktok: string;
  facebook: string;
  twitter: string;
  youtubeChannel: string;
  bookingEmail: string;
  newsletterUrl: string;
  // Step 4 — Release
  releaseTitle: string;
  releaseType: "album" | "ep" | "single" | "live";
  releaseDate: string;
  releaseDescription: string;
  tracks: TrackInput[];
}

const EMPTY: FormData = {
  name: "", genre: "", tagline: "", origin: "", founded: "",
  bio: ["", ""],
  members: [{ name: "", role: "" }, { name: "", role: "" }],
  awards: "",
  spotify: "", appleMusic: "", youtube: "", soundcloud: "", bandcamp: "",
  instagram: "", tiktok: "", facebook: "", twitter: "", youtubeChannel: "",
  bookingEmail: "", newsletterUrl: "",
  releaseTitle: "", releaseType: "album", releaseDate: "", releaseDescription: "",
  tracks: [{ number: 1, title: "", duration: "" }],
};

const STEPS = ["Identity", "Story", "Links", "Release", "Generate"];

// ─── Helpers ──────────────────────────────────────────────────────

function slugify(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function buildDataTs(f: FormData): string {
  const slug = slugify(f.name);
  const genres = f.genre.split(",").map((g) => g.trim()).filter(Boolean);
  const bioLines = f.bio.filter((b) => b.trim());
  const members = f.members.filter((m) => m.name.trim());
  const awards = f.awards.split("\n").map((a) => a.trim()).filter(Boolean);
  const tracks = f.tracks.filter((t) => t.title.trim());

  return `// BandStack · Generated by Intake Form
// Artist: ${f.name}

import { Artist, Release, Show } from "./types";

export const artist: Artist = {
  name: ${JSON.stringify(f.name)},
  slug: ${JSON.stringify(slug)},
  tagline: ${JSON.stringify(f.tagline)},
  bio: ${JSON.stringify(bioLines, null, 2)},
  origin: ${JSON.stringify(f.origin)},
  genre: ${JSON.stringify(genres)},
  founded: ${parseInt(f.founded) || new Date().getFullYear()},
  members: ${JSON.stringify(members, null, 2)},
  pressQuotes: [],
  awards: ${JSON.stringify(awards, null, 2)},
  socialLinks: {
    instagram:  ${JSON.stringify(f.instagram  || undefined)},
    tiktok:     ${JSON.stringify(f.tiktok     || undefined)},
    facebook:   ${JSON.stringify(f.facebook   || undefined)},
    twitter:    ${JSON.stringify(f.twitter    || undefined)},
    youtube:    ${JSON.stringify(f.youtubeChannel || undefined)},
  },
  streamingLinks: {
    spotify:    ${JSON.stringify(f.spotify    || undefined)},
    appleMusic: ${JSON.stringify(f.appleMusic || undefined)},
    youtube:    ${JSON.stringify(f.youtube    || undefined)},
    soundcloud: ${JSON.stringify(f.soundcloud || undefined)},
    bandcamp:   ${JSON.stringify(f.bandcamp   || undefined)},
  },
  bookingEmail:  ${JSON.stringify(f.bookingEmail  || undefined)},
  newsletterUrl: ${JSON.stringify(f.newsletterUrl || undefined)},
};

export const releases: Release[] = [
  {
    slug: ${JSON.stringify(slugify(f.releaseTitle || "untitled"))},
    title: ${JSON.stringify(f.releaseTitle)},
    type: ${JSON.stringify(f.releaseType)},
    releaseDate: ${JSON.stringify(f.releaseDate)},
    description: ${JSON.stringify(f.releaseDescription || undefined)},
    coverArt: undefined,
    isFeatured: true,
    streamingLinks: {
      spotify:    ${JSON.stringify(f.spotify    || undefined)},
      appleMusic: ${JSON.stringify(f.appleMusic || undefined)},
      youtube:    ${JSON.stringify(f.youtube    || undefined)},
    },
    tracks: ${JSON.stringify(tracks.map((t) => ({
      number: t.number,
      title: t.title,
      ...(t.duration ? { duration: t.duration } : {}),
    })), null, 4)},
  },
];

export const shows: Show[] = [];
`;
}

// ─── Shared input styles ──────────────────────────────────────────

function inputStyle(tokens: TokenSet): React.CSSProperties {
  return {
    width: "100%",
    background: tokens.bg3,
    border: `1px solid ${tokens.border2}`,
    borderRadius: "6px",
    color: tokens.text,
    fontFamily: `'Inter', system-ui, sans-serif`,
    fontSize: "0.88rem",
    padding: "10px 14px",
    outline: "none",
    lineHeight: 1.5,
  };
}

function labelStyle(tokens: TokenSet): React.CSSProperties {
  return {
    display: "block",
    fontFamily: "monospace",
    fontSize: "0.6rem",
    letterSpacing: "0.16em",
    textTransform: "uppercase" as const,
    color: tokens.muted,
    marginBottom: "6px",
  };
}

function fieldStyle(): React.CSSProperties {
  return { marginBottom: "1.25rem" };
}

// ─── Step components ──────────────────────────────────────────────

function StepIdentity({ f, set, tokens }: { f: FormData; set: (k: keyof FormData, v: unknown) => void; tokens: TokenSet }) {
  const genres = Object.keys(TOKENS);
  const iStyle = inputStyle(tokens);
  const lStyle = labelStyle(tokens);

  return (
    <div>
      <div style={fieldStyle()}>
        <label style={lStyle}>Band / Artist Name *</label>
        <input style={iStyle} value={f.name} onChange={(e) => set("name", e.target.value)} placeholder="Ryan Chrys & The Rough Cuts" />
      </div>
      <div style={fieldStyle()}>
        <label style={lStyle}>Genre *</label>
        <select
          style={{ ...iStyle, cursor: "pointer" }}
          value={f.genre}
          onChange={(e) => set("genre", e.target.value)}
        >
          <option value="">— select genre —</option>
          {genres.map((g) => (
            <option key={g} value={g}>{g.charAt(0).toUpperCase() + g.slice(1)}</option>
          ))}
        </select>
        {f.genre && (
          <p style={{ fontFamily: "monospace", fontSize: "0.58rem", color: tokens.accent, marginTop: "6px" }}>
            ↑ Font: {tokens.displayFont} + {tokens.bodyFont} · Accent: {tokens.accent}
          </p>
        )}
      </div>
      <div style={fieldStyle()}>
        <label style={lStyle}>Tagline</label>
        <input style={iStyle} value={f.tagline} onChange={(e) => set("tagline", e.target.value)} placeholder="Modern outlaw country. Denver-born. Road-hardened." />
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
        <div style={fieldStyle()}>
          <label style={lStyle}>Origin (City, State)</label>
          <input style={iStyle} value={f.origin} onChange={(e) => set("origin", e.target.value)} placeholder="Denver, Colorado" />
        </div>
        <div style={fieldStyle()}>
          <label style={lStyle}>Founded (Year)</label>
          <input style={iStyle} value={f.founded} onChange={(e) => set("founded", e.target.value)} placeholder="2004" type="number" />
        </div>
      </div>
    </div>
  );
}

function StepStory({ f, set, tokens }: { f: FormData; set: (k: keyof FormData, v: unknown) => void; tokens: TokenSet }) {
  const iStyle = inputStyle(tokens);
  const lStyle = labelStyle(tokens);

  const updateBio = (i: number, val: string) => {
    const next = [...f.bio];
    next[i] = val;
    set("bio", next);
  };
  const addBio = () => set("bio", [...f.bio, ""]);

  const updateMember = (i: number, field: "name" | "role", val: string) => {
    const next = [...f.members];
    next[i] = { ...next[i], [field]: val };
    set("members", next);
  };
  const addMember = () => set("members", [...f.members, { name: "", role: "" }]);

  return (
    <div>
      <div style={fieldStyle()}>
        <label style={lStyle}>Bio Paragraphs</label>
        {f.bio.map((para, i) => (
          <textarea
            key={i}
            style={{ ...iStyle, display: "block", minHeight: 90, resize: "vertical", marginBottom: "0.5rem" }}
            value={para}
            onChange={(e) => updateBio(i, e.target.value)}
            placeholder={i === 0 ? "Primary bio paragraph — who you are, what you sound like..." : "Second paragraph — history, influences, accolades..."}
          />
        ))}
        <button
          type="button"
          onClick={addBio}
          style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.12em", color: tokens.accent, background: "transparent", border: `1px solid ${tokens.border2}`, borderRadius: "4px", padding: "5px 12px", cursor: "pointer" }}
        >
          + Add paragraph
        </button>
      </div>

      <div style={fieldStyle()}>
        <label style={lStyle}>Members</label>
        {f.members.map((m, i) => (
          <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.5rem", marginBottom: "0.5rem" }}>
            <input style={iStyle} value={m.name} onChange={(e) => updateMember(i, "name", e.target.value)} placeholder="Name" />
            <input style={iStyle} value={m.role} onChange={(e) => updateMember(i, "role", e.target.value)} placeholder="Role (Lead Vocals, Guitar...)" />
          </div>
        ))}
        <button
          type="button"
          onClick={addMember}
          style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.12em", color: tokens.accent, background: "transparent", border: `1px solid ${tokens.border2}`, borderRadius: "4px", padding: "5px 12px", cursor: "pointer" }}
        >
          + Add member
        </button>
      </div>

      <div style={fieldStyle()}>
        <label style={lStyle}>Awards & Accolades (one per line)</label>
        <textarea
          style={{ ...iStyle, minHeight: 80, resize: "vertical" }}
          value={f.awards}
          onChange={(e) => set("awards", e.target.value)}
          placeholder={"Colorado Country Music Hall of Fame Inductees, 2025\nBand of the Year — CCMHF, 2019"}
        />
      </div>
    </div>
  );
}

function StepLinks({ f, set, tokens }: { f: FormData; set: (k: keyof FormData, v: unknown) => void; tokens: TokenSet }) {
  const iStyle = inputStyle(tokens);
  const lStyle = labelStyle(tokens);

  const field = (label: string, key: keyof FormData, ph: string) => (
    <div style={fieldStyle()}>
      <label style={lStyle}>{label}</label>
      <input style={iStyle} value={f[key] as string} onChange={(e) => set(key, e.target.value)} placeholder={ph} />
    </div>
  );

  return (
    <div>
      <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", color: tokens.muted2, textTransform: "uppercase", marginBottom: "1.25rem" }}>Streaming</p>
      {field("Spotify Artist URL", "spotify", "https://open.spotify.com/artist/...")}
      {field("Apple Music URL", "appleMusic", "https://music.apple.com/...")}
      {field("YouTube Music / Channel URL", "youtube", "https://www.youtube.com/...")}
      {field("SoundCloud URL", "soundcloud", "https://soundcloud.com/...")}
      {field("Bandcamp URL", "bandcamp", "https://yourband.bandcamp.com")}

      <div style={{ height: 1, background: tokens.border, margin: "1.5rem 0" }} />
      <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", color: tokens.muted2, textTransform: "uppercase", marginBottom: "1.25rem" }}>Social</p>
      {field("Instagram URL", "instagram", "https://instagram.com/yourband")}
      {field("TikTok URL", "tiktok", "https://tiktok.com/@yourband")}
      {field("Facebook URL", "facebook", "https://facebook.com/yourband")}
      {field("Twitter / X URL", "twitter", "https://twitter.com/yourband")}
      {field("YouTube Channel URL", "youtubeChannel", "https://youtube.com/@YourBand")}

      <div style={{ height: 1, background: tokens.border, margin: "1.5rem 0" }} />
      <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", color: tokens.muted2, textTransform: "uppercase", marginBottom: "1.25rem" }}>Contact</p>
      {field("Booking Email", "bookingEmail", "booking@yourband.com")}
      {field("Newsletter / Fan Club URL", "newsletterUrl", "https://yourband.com/subscribe")}
    </div>
  );
}

function StepRelease({ f, set, tokens }: { f: FormData; set: (k: keyof FormData, v: unknown) => void; tokens: TokenSet }) {
  const iStyle = inputStyle(tokens);
  const lStyle = labelStyle(tokens);

  const updateTrack = (i: number, field: keyof TrackInput, val: string | number) => {
    const next = [...f.tracks];
    next[i] = { ...next[i], [field]: val };
    set("tracks", next);
  };
  const addTrack = () => set("tracks", [...f.tracks, { number: f.tracks.length + 1, title: "", duration: "" }]);

  return (
    <div>
      <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", color: tokens.muted2, textTransform: "uppercase", marginBottom: "1.25rem" }}>Featured Release</p>
      <div style={fieldStyle()}>
        <label style={lStyle}>Album / EP / Single Title *</label>
        <input style={iStyle} value={f.releaseTitle} onChange={(e) => set("releaseTitle", e.target.value)} placeholder="Blame It On the Road" />
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
        <div style={fieldStyle()}>
          <label style={lStyle}>Type</label>
          <select style={{ ...iStyle, cursor: "pointer" }} value={f.releaseType} onChange={(e) => set("releaseType", e.target.value as "album" | "ep" | "single" | "live")}>
            <option value="album">Album</option>
            <option value="ep">EP</option>
            <option value="single">Single</option>
            <option value="live">Live</option>
          </select>
        </div>
        <div style={fieldStyle()}>
          <label style={lStyle}>Release Date</label>
          <input style={iStyle} type="date" value={f.releaseDate} onChange={(e) => set("releaseDate", e.target.value)} />
        </div>
      </div>
      <div style={fieldStyle()}>
        <label style={lStyle}>Description (optional)</label>
        <textarea style={{ ...iStyle, minHeight: 72, resize: "vertical" }} value={f.releaseDescription} onChange={(e) => set("releaseDescription", e.target.value)} placeholder="A stripped-down collection recorded live at..." />
      </div>

      <div style={fieldStyle()}>
        <label style={lStyle}>Tracks</label>
        {f.tracks.map((t, i) => (
          <div key={i} style={{ display: "grid", gridTemplateColumns: "40px 1fr 100px", gap: "0.5rem", marginBottom: "0.5rem", alignItems: "center" }}>
            <span style={{ fontFamily: "monospace", fontSize: "0.75rem", color: tokens.muted2, textAlign: "center" }}>{t.number}</span>
            <input style={iStyle} value={t.title} onChange={(e) => updateTrack(i, "title", e.target.value)} placeholder="Track title" />
            <input style={iStyle} value={t.duration} onChange={(e) => updateTrack(i, "duration", e.target.value)} placeholder="3:42" />
          </div>
        ))}
        <button
          type="button"
          onClick={addTrack}
          style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.12em", color: tokens.accent, background: "transparent", border: `1px solid ${tokens.border2}`, borderRadius: "4px", padding: "5px 12px", cursor: "pointer" }}
        >
          + Add track
        </button>
      </div>
    </div>
  );
}

function StepGenerate({ f, tokens }: { f: FormData; tokens: TokenSet }) {
  const [copied, setCopied] = useState(false);
  const output = buildDataTs(f);

  const copy = () => {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const download = () => {
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "data.ts";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div>
      <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", color: tokens.muted2, textTransform: "uppercase", marginBottom: "1rem" }}>Generated data.ts</p>

      {/* Actions */}
      <div style={{ display: "flex", gap: "0.75rem", marginBottom: "1.25rem" }}>
        <button
          type="button"
          onClick={copy}
          style={{
            fontFamily: "monospace", fontSize: "0.62rem", letterSpacing: "0.14em",
            textTransform: "uppercase",
            background: tokens.accent, color: "#000",
            border: "none", borderRadius: "6px", padding: "10px 20px", cursor: "pointer",
            fontWeight: 600,
          }}
        >
          {copied ? "✓ Copied" : "Copy to Clipboard"}
        </button>
        <button
          type="button"
          onClick={download}
          style={{
            fontFamily: "monospace", fontSize: "0.62rem", letterSpacing: "0.14em",
            textTransform: "uppercase",
            background: "transparent", color: tokens.accent,
            border: `1px solid ${tokens.border2}`, borderRadius: "6px", padding: "10px 20px", cursor: "pointer",
          }}
        >
          Download data.ts
        </button>
      </div>

      {/* Code block */}
      <pre
        style={{
          background: tokens.bg3,
          border: `1px solid ${tokens.border}`,
          borderRadius: "8px",
          padding: "20px",
          overflowX: "auto",
          fontFamily: "'Space Mono', monospace",
          fontSize: "0.72rem",
          lineHeight: 1.65,
          color: tokens.text,
          whiteSpace: "pre",
          maxHeight: 480,
          overflowY: "auto",
        }}
      >
        {output}
      </pre>

      {/* Next steps */}
      <div style={{ marginTop: "2rem", padding: "1.25rem 1.5rem", background: tokens.bg2, border: `1px solid ${tokens.border}`, borderLeft: `3px solid ${tokens.accent}`, borderRadius: "8px" }}>
        <p style={{ fontFamily: "monospace", fontSize: "0.6rem", letterSpacing: "0.14em", textTransform: "uppercase", color: tokens.accent, marginBottom: "0.75rem" }}>Next Steps</p>
        <ol style={{ fontFamily: `'Inter', system-ui, sans-serif`, fontSize: "0.84rem", color: tokens.text, lineHeight: 1.8, paddingLeft: "1.25rem" }}>
          <li>Copy or download <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>data.ts</code></li>
          <li>Drop it into your BandStack project at <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>lib/data.ts</code></li>
          <li>Replace any <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>undefined</code> fields with real URLs</li>
          <li>Add cover art to <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>public/</code> and set <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>coverArt</code></li>
          <li>Run <code style={{ fontFamily: "monospace", fontSize: "0.78rem", color: tokens.accentWarm }}>npm run dev</code> — your site is live</li>
        </ol>
      </div>
    </div>
  );
}

// ─── Main form ────────────────────────────────────────────────────

export default function IntakeForm() {
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<FormData>(EMPTY);

  const set = useCallback((k: keyof FormData, v: unknown) => {
    setForm((prev) => ({ ...prev, [k]: v }));
  }, []);

  const tokens = form.genre
    ? resolveTokens([form.genre])
    : { bg: "#0c0b09", bg2: "#141210", bg3: "#1d1a16", border: "rgba(255,220,150,0.06)", border2: "rgba(255,220,150,0.12)", accent: "#888", accentWarm: "#aaa", accentDim: "rgba(136,136,136,0.10)", text: "#ede8df", muted: "rgba(237,232,223,0.5)", muted2: "rgba(237,232,223,0.25)", displayFont: "Bebas Neue", bodyFont: "Inter", displayFontUrl: "", bodyFontUrl: "" } as TokenSet;

  const canProceed = () => {
    if (step === 0) return f.name.trim().length > 0 && f.genre.length > 0;
    return true;
  };
  const f = form;

  const stepContent = [
    <StepIdentity key="1" f={f} set={set} tokens={tokens} />,
    <StepStory    key="2" f={f} set={set} tokens={tokens} />,
    <StepLinks    key="3" f={f} set={set} tokens={tokens} />,
    <StepRelease  key="4" f={f} set={set} tokens={tokens} />,
    <StepGenerate key="5" f={f} tokens={tokens} />,
  ];

  return (
    <main style={{ minHeight: "100vh", background: tokens.bg, transition: "background 0.4s ease" }}>

      {/* Top bar */}
      <header style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        background: "rgba(12,11,9,0.85)",
        backdropFilter: "blur(16px)",
        WebkitBackdropFilter: "blur(16px)",
        borderBottom: `1px solid ${tokens.border}`,
        height: 56,
        display: "flex", alignItems: "center",
        padding: "0 32px",
        justifyContent: "space-between",
      }}>
        <span style={{ fontFamily: `'Bebas Neue', sans-serif`, fontSize: "1.1rem", letterSpacing: "0.06em", color: tokens.text }}>
          BandStack
        </span>
        {/* Progress pills */}
        <div style={{ display: "flex", gap: "0.4rem" }}>
          {STEPS.map((s, i) => (
            <button
              key={s}
              type="button"
              onClick={() => i < step + 1 && setStep(i)}
              style={{
                fontFamily: "monospace", fontSize: "0.52rem", letterSpacing: "0.14em",
                textTransform: "uppercase",
                padding: "4px 10px", borderRadius: "9999px",
                border: "1px solid",
                cursor: i <= step ? "pointer" : "default",
                borderColor: i === step ? tokens.accent : i < step ? tokens.border2 : tokens.border,
                background: i === step ? tokens.accentDim : "transparent",
                color: i === step ? tokens.accent : i < step ? tokens.muted : tokens.muted2,
                transition: "all 0.2s ease",
              }}
            >
              {s}
            </button>
          ))}
        </div>
      </header>

      {/* Content */}
      <div style={{ maxWidth: 620, margin: "0 auto", padding: "96px 28px 80px" }}>

        {/* Step heading */}
        <div style={{ marginBottom: "2.5rem" }}>
          <p style={{
            fontFamily: "monospace", fontSize: "0.58rem", letterSpacing: "0.2em",
            textTransform: "uppercase", color: tokens.accent, marginBottom: "0.4rem",
          }}>
            Step {step + 1} of {STEPS.length}
          </p>
          <h1 style={{
            fontFamily: `'Bebas Neue', var(--display-font, sans-serif)`,
            fontSize: "clamp(2rem, 5vw, 3.5rem)",
            lineHeight: 1, color: tokens.text,
            letterSpacing: "0.02em",
          }}>
            {["Who Are You?", "Tell Your Story", "Your Links", "Your Music", "You're Done."][step]}
          </h1>
          {step === 0 && f.genre && (
            <div style={{
              display: "inline-flex", alignItems: "center", gap: "8px",
              marginTop: "0.75rem", padding: "5px 14px",
              background: tokens.accentDim,
              border: `1px solid ${tokens.border2}`,
              borderRadius: "9999px",
            }}>
              <span style={{ width: 10, height: 10, borderRadius: "50%", background: tokens.accent, display: "inline-block" }} />
              <span style={{ fontFamily: "monospace", fontSize: "0.58rem", letterSpacing: "0.12em", color: tokens.accent }}>
                {f.genre} · {tokens.displayFont}
              </span>
            </div>
          )}
        </div>

        {/* Active step */}
        {stepContent[step]}

        {/* Navigation */}
        <div style={{
          display: "flex", justifyContent: "space-between",
          marginTop: "2.5rem", paddingTop: "1.5rem",
          borderTop: `1px solid ${tokens.border}`,
        }}>
          <button
            type="button"
            onClick={() => setStep((s) => Math.max(0, s - 1))}
            disabled={step === 0}
            style={{
              fontFamily: "monospace", fontSize: "0.62rem", letterSpacing: "0.14em",
              textTransform: "uppercase",
              background: "transparent", color: step === 0 ? tokens.muted2 : tokens.muted,
              border: `1px solid ${step === 0 ? tokens.border : tokens.border2}`,
              borderRadius: "6px", padding: "10px 22px",
              cursor: step === 0 ? "default" : "pointer",
            }}
          >
            ← Back
          </button>

          {step < STEPS.length - 1 && (
            <button
              type="button"
              onClick={() => setStep((s) => Math.min(STEPS.length - 1, s + 1))}
              disabled={!canProceed()}
              style={{
                fontFamily: "monospace", fontSize: "0.62rem", letterSpacing: "0.14em",
                textTransform: "uppercase",
                background: canProceed() ? tokens.accent : tokens.bg3,
                color: canProceed() ? "#000" : tokens.muted2,
                border: "none", borderRadius: "6px", padding: "10px 22px",
                cursor: canProceed() ? "pointer" : "default",
                fontWeight: 600,
                transition: "background 0.2s ease",
              }}
            >
              {step === STEPS.length - 2 ? "Generate →" : "Next →"}
            </button>
          )}
        </div>
      </div>

    </main>
  );
}
