"use client";

import { useState, useCallback, useEffect } from "react";
import { TOKENS, resolveTokens, TokenSet } from "@/lib/genreTokens";

// ─── Types ────────────────────────────────────────────────────────

interface MemberInput     { name: string; role: string; }
interface TrackInput      { number: number; title: string; duration: string; }
interface PressQuoteInput { quote: string; source: string; year: string; url: string; }

interface FormData {
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  name: string;
  genre: string;
  tagline: string;
  origin: string;
  founded: string;
  website: string;
  bookingEmail: string;
  bookingContact: string;
  managementName: string;
  managementEmail: string;
  pressContactName: string;
  pressContactEmail: string;
  merchUrl: string;
  bio: string[];
  members: MemberInput[];
  awards: string;
  pressQuotes: PressQuoteInput[];
  pressPhotoUrls: string;
  onesheetUrl: string;
  spotify: string;
  appleMusic: string;
  youtube: string;
  soundcloud: string;
  bandcamp: string;
  instagram: string;
  tiktok: string;
  facebook: string;
  twitter: string;
  threads: string;
  youtubeChannel: string;
  newsletterUrl: string;
  releaseTitle: string;
  releaseType: "album" | "ep" | "single" | "live";
  releaseDate: string;
  releaseDescription: string;
  tracks: TrackInput[];
}

const EMPTY: FormData = {
  contactName: "", contactEmail: "", contactPhone: "",
  name: "", genre: "", tagline: "", origin: "", founded: "",
  website: "",
  bookingEmail: "", bookingContact: "",
  managementName: "", managementEmail: "",
  pressContactName: "", pressContactEmail: "",
  merchUrl: "",
  bio: [""],
  members: [{ name: "", role: "" }],
  awards: "",
  pressQuotes: [{ quote: "", source: "", year: "", url: "" }],
  pressPhotoUrls: "",
  onesheetUrl: "",
  spotify: "", appleMusic: "", youtube: "", soundcloud: "", bandcamp: "",
  instagram: "", tiktok: "", facebook: "", twitter: "", threads: "", youtubeChannel: "",
  newsletterUrl: "",
  releaseTitle: "", releaseType: "album", releaseDate: "", releaseDescription: "",
  tracks: [{ number: 1, title: "", duration: "" }],
};

type Setter = (k: keyof FormData, v: unknown) => void;

// ─── Helpers ──────────────────────────────────────────────────────

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

function buildDataTs(f: FormData): string {
  const slug = slugify(f.name);
  const genres = f.genre.split(",").map((g) => g.trim()).filter(Boolean);
  const bioLines = f.bio.filter((b) => b.trim());
  const members = f.members.filter((m) => m.name.trim());
  const awards = f.awards.split("\n").map((a) => a.trim()).filter(Boolean);
  const tracks = f.tracks.filter((t) => t.title.trim());
  const pressQuotes = f.pressQuotes.filter((q) => q.quote.trim() && q.source.trim());
  const pressPhotos = f.pressPhotoUrls.split("\n").map((u) => u.trim()).filter(Boolean);

  return `// BandStack · Generated by Intake Form
// Artist: ${f.name}

import { Artist, Release, Show } from "./types";

export const artist: Artist = {
  name: ${JSON.stringify(f.name)},
  slug: ${JSON.stringify(slug)},
  tagline: ${JSON.stringify(f.tagline)},
  bio: ${JSON.stringify(bioLines, null, 2)},
  origin: ${JSON.stringify(f.origin)},
  genre: ${JSON.stringify(genres)},
  founded: ${parseInt(f.founded) || new Date().getFullYear()},
  members: ${JSON.stringify(members, null, 2)},
  pressQuotes: ${JSON.stringify(pressQuotes.map((q) => ({
    quote: q.quote,
    source: q.source,
    ...(q.year ? { year: parseInt(q.year) } : {}),
    ...(q.url ? { url: q.url } : {}),
  })), null, 4)},
  awards: ${JSON.stringify(awards, null, 2)},
  website: ${JSON.stringify(f.website || undefined)},
  merchUrl: ${JSON.stringify(f.merchUrl || undefined)},
  bookingEmail:   ${JSON.stringify(f.bookingEmail   || undefined)},
  bookingContact: ${JSON.stringify(f.bookingContact || undefined)},
  managementName:  ${JSON.stringify(f.managementName  || undefined)},
  managementEmail: ${JSON.stringify(f.managementEmail || undefined)},
  pressContactName:  ${JSON.stringify(f.pressContactName  || undefined)},
  pressContactEmail: ${JSON.stringify(f.pressContactEmail || undefined)},
  pressPhotoUrls: ${JSON.stringify(pressPhotos.length ? pressPhotos : undefined)},
  onesheetUrl: ${JSON.stringify(f.onesheetUrl || undefined)},
  socialLinks: {
    instagram:  ${JSON.stringify(f.instagram  || undefined)},
    tiktok:     ${JSON.stringify(f.tiktok     || undefined)},
    facebook:   ${JSON.stringify(f.facebook   || undefined)},
    twitter:    ${JSON.stringify(f.twitter    || undefined)},
    threads:    ${JSON.stringify(f.threads    || undefined)},
    youtube:    ${JSON.stringify(f.youtubeChannel || undefined)},
  },
  streamingLinks: {
    spotify:    ${JSON.stringify(f.spotify    || undefined)},
    appleMusic: ${JSON.stringify(f.appleMusic || undefined)},
    youtube:    ${JSON.stringify(f.youtube    || undefined)},
    soundcloud: ${JSON.stringify(f.soundcloud || undefined)},
    bandcamp:   ${JSON.stringify(f.bandcamp   || undefined)},
  },
  newsletterUrl: ${JSON.stringify(f.newsletterUrl || undefined)},
};

export const releases: Release[] = [
  {
    slug: ${JSON.stringify(slugify(f.releaseTitle || "untitled"))},
    title: ${JSON.stringify(f.releaseTitle)},
    type: ${JSON.stringify(f.releaseType)},
    releaseDate: ${JSON.stringify(f.releaseDate)},
    description: ${JSON.stringify(f.releaseDescription || undefined)},
    coverArt: undefined,
    isFeatured: true,
    streamingLinks: {
      spotify:    ${JSON.stringify(f.spotify    || undefined)},
      appleMusic: ${JSON.stringify(f.appleMusic || undefined)},
      youtube:    ${JSON.stringify(f.youtube    || undefined)},
    },
    tracks: ${JSON.stringify(tracks.map((t) => ({
      number: t.number,
      title: t.title,
      ...(t.duration ? { duration: t.duration } : {}),
    })), null, 4)},
  },
];

export const shows: Show[] = [];
`;
}

// ─── Default tokens (pre-genre) ───────────────────────────────────

const DEFAULT_TOKENS: TokenSet = {
  bg: "#080808", bg2: "#111", bg3: "#181818",
  border: "rgba(255,255,255,0.06)", border2: "rgba(255,255,255,0.12)",
  accent: "#555", accentWarm: "#666", accentDim: "rgba(85,85,85,0.12)",
  text: "#e8e8e8", muted: "rgba(232,232,232,0.45)", muted2: "rgba(232,232,232,0.22)",
  displayFont: "Bebas Neue", bodyFont: "Inter", displayFontUrl: "", bodyFontUrl: "",
};

// ─── Shared field components ──────────────────────────────────────

function QInput({
  value, onChange, placeholder, tokens, onEnter, type = "text", autoFocus = true,
}: {
  value: string; onChange: (v: string) => void; placeholder: string;
  tokens: TokenSet; onEnter: () => void; type?: string; autoFocus?: boolean;
}) {
  const [focused, setFocused] = useState(false);
  const hasValue = value.trim().length > 0;
  return (
    <div>
      <input
        autoFocus={autoFocus}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        onFocus={() => setFocused(true)}
        onBlur={() => setFocused(false)}
        onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); onEnter(); } }}
        placeholder={placeholder}
        style={{
          width: "100%", background: "transparent", border: "none",
          borderBottom: `2px solid ${focused ? tokens.accent : "rgba(232,232,232,0.25)"}`,
          color: tokens.text,
          fontSize: "clamp(1.1rem, 2.8vw, 1.5rem)",
          fontFamily: "'Inter', system-ui, sans-serif",
          fontWeight: 300, padding: "10px 0 14px", outline: "none",
          letterSpacing: "0.01em", transition: "border-color 0.3s ease",
          caretColor: tokens.accent,
        }}
      />
      <p style={{
        fontFamily: "'Inter', system-ui, sans-serif",
        fontSize: "0.72rem", letterSpacing: "0.08em",
        color: hasValue ? "rgba(232,232,232,0.25)" : "transparent",
        marginTop: "0.6rem", transition: "color 0.3s ease",
        fontWeight: 300,
      }}>
        press enter to continue
      </p>
    </div>
  );
}

function QTextarea({
  value, onChange, placeholder, tokens, rows = 5,
}: {
  value: string; onChange: (v: string) => void; placeholder: string;
  tokens: TokenSet; rows?: number;
}) {
  const [focused, setFocused] = useState(false);
  return (
    <textarea
      autoFocus
      rows={rows}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      placeholder={placeholder}
      style={{
        width: "100%", background: "transparent", border: "none",
        borderBottom: `2px solid ${focused ? tokens.accent : tokens.border2}`,
        color: tokens.text,
        fontSize: "clamp(1rem, 2.5vw, 1.25rem)",
        fontFamily: "'Inter', system-ui, sans-serif",
        fontWeight: 300, padding: "10px 0 14px", outline: "none",
        letterSpacing: "0.01em", transition: "border-color 0.2s ease",
        caretColor: tokens.accent, resize: "none", lineHeight: 1.7,
      }}
    />
  );
}

function SmallInput({
  value, onChange, placeholder, tokens, type = "text", autoFocus = false,
}: {
  value: string; onChange: (v: string) => void; placeholder: string;
  tokens: TokenSet; type?: string; autoFocus?: boolean;
}) {
  const [focused, setFocused] = useState(false);
  return (
    <input
      autoFocus={autoFocus}
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      onFocus={() => setFocused(true)}
      onBlur={() => setFocused(false)}
      placeholder={placeholder}
      style={{
        width: "100%", background: "rgba(255,255,255,0.03)",
        border: `1px solid ${focused ? tokens.accent : tokens.border2}`,
        borderRadius: 6, color: tokens.text,
        fontSize: "0.88rem",
        fontFamily: "'Inter', system-ui, sans-serif",
        padding: "9px 14px", outline: "none",
        transition: "border-color 0.2s ease",
        caretColor: tokens.accent,
      }}
    />
  );
}

function FieldLabel({ label, tokens }: { label: string; tokens: TokenSet }) {
  return (
    <p style={{
      fontFamily: "monospace", fontSize: "0.58rem", letterSpacing: "0.18em",
      textTransform: "uppercase", color: tokens.muted2, marginBottom: "8px",
    }}>
      {label}
    </p>
  );
}

function AddBtn({ onClick, label, tokens }: { onClick: () => void; label: string; tokens: TokenSet }) {
  return (
    <button type="button" onClick={onClick} style={{
      fontFamily: "monospace", fontSize: "0.58rem", letterSpacing: "0.12em",
      color: tokens.accent, background: "transparent",
      border: `1px solid ${tokens.border2}`, borderRadius: 4,
      padding: "5px 12px", cursor: "pointer", marginTop: 8,
    }}>
      {label}
    </button>
  );
}

// ─── Genre Selector ───────────────────────────────────────────────

function GenreSelector({ f, set, tokens }: { f: FormData; set: Setter; tokens: TokenSet }) {
  const genres = Object.keys(TOKENS);
  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: "0.6rem", marginTop: "0.5rem" }}>
      {genres.map((g) => {
        const gt = resolveTokens([g]);
        const selected = f.genre === g;
        return (
          <button
            key={g}
            type="button"
            onClick={() => set("genre", g)}
            style={{
              fontFamily: "'Inter', system-ui, sans-serif",
              fontSize: "0.9rem", fontWeight: selected ? 500 : 400,
              padding: "10px 20px", borderRadius: "9999px",
              border: `1.5px solid ${selected ? gt.accent : tokens.border2}`,
              background: selected ? gt.accentDim : "rgba(255,255,255,0.03)",
              color: selected ? gt.accent : tokens.muted,
              cursor: "pointer",
              transition: "all 0.18s ease",
              letterSpacing: "0.01em",
            }}
          >
            {selected && (
              <span style={{
                display: "inline-block", width: 7, height: 7, borderRadius: "50%",
                background: gt.accent, marginRight: 8, verticalAlign: "middle",
              }} />
            )}
            {g.charAt(0).toUpperCase() + g.slice(1)}
          </button>
        );
      })}
    </div>
  );
}

// ─── Member Builder ───────────────────────────────────────────────

function MemberBuilder({ f, set, tokens }: { f: FormData; set: Setter; tokens: TokenSet }) {
  const update = (i: number, field: "name" | "role", val: string) => {
    const next = [...f.members];
    next[i] = { ...next[i], [field]: val };
    set("members", next);
  };
  return (
    <div>
      {f.members.map((m, i) => (
        <div key={i} style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem", marginBottom: "1rem" }}>
          <div>
            <FieldLabel label="Name" tokens={tokens} />
            <SmallInput value={m.name} onChange={(v) => update(i, "name", v)} placeholder="Ryan Chrys" tokens={tokens} autoFocus={i === 0} />
          </div>
          <div>
            <FieldLabel label="Role" tokens={tokens} />
            <SmallInput value={m.role} onChange={(v) => update(i, "role", v)} placeholder="Lead Vocals, Guitar" tokens={tokens} />
          </div>
        </div>
      ))}
      <AddBtn onClick={() => set("members", [...f.members, { name: "", role: "" }])} label="+ Add member" tokens={tokens} />
    </div>
  );
}

// ─── Press Quote Builder ──────────────────────────────────────────

function QuoteBuilder({ f, set, tokens }: { f: FormData; set: Setter; tokens: TokenSet }) {
  const update = (i: number, field: keyof PressQuoteInput, val: string) => {
    const next = [...f.pressQuotes];
    next[i] = { ...next[i], [field]: val };
    set("pressQuotes", next);
  };
  return (
    <div>
      {f.pressQuotes.map((q, i) => (
        <div key={i} style={{
          borderLeft: `2px solid ${tokens.border2}`, paddingLeft: "1.25rem",
          marginBottom: "1.75rem",
        }}>
          <div style={{ marginBottom: "0.75rem" }}>
            <FieldLabel label="The quote" tokens={tokens} />
            <SmallInput value={q.quote} onChange={(v) => update(i, "quote", v)} placeholder="One of the hardest-working bands on the circuit..." tokens={tokens} autoFocus={i === 0} />
          </div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 80px 1fr", gap: "0.75rem" }}>
            <div>
              <FieldLabel label="Source" tokens={tokens} />
              <SmallInput value={q.source} onChange={(v) => update(i, "source", v)} placeholder="Westword" tokens={tokens} />
            </div>
            <div>
              <FieldLabel label="Year" tokens={tokens} />
              <SmallInput value={q.year} onChange={(v) => update(i, "year", v)} placeholder="2024" tokens={tokens} />
            </div>
            <div>
              <FieldLabel label="Link" tokens={tokens} />
              <SmallInput value={q.url} onChange={(v) => update(i, "url", v)} placeholder="https://..." tokens={tokens} />
            </div>
          </div>
        </div>
      ))}
      <AddBtn onClick={() => set("pressQuotes", [...f.pressQuotes, { quote: "", source: "", year: "", url: "" }])} label="+ Add another quote" tokens={tokens} />
    </div>
  );
}

// ─── Track Builder ────────────────────────────────────────────────

function TrackBuilder({ f, set, tokens }: { f: FormData; set: Setter; tokens: TokenSet }) {
  const update = (i: number, field: keyof TrackInput, val: string | number) => {
    const next = [...f.tracks];
    next[i] = { ...next[i], [field]: val };
    set("tracks", next);
  };
  return (
    <div>
      {f.tracks.map((t, i) => (
        <div key={i} style={{ display: "grid", gridTemplateColumns: "36px 1fr 90px", gap: "0.75rem", marginBottom: "0.75rem", alignItems: "center" }}>
          <span style={{ fontFamily: "monospace", fontSize: "0.72rem", color: tokens.muted2, textAlign: "right" }}>
            {t.number}
          </span>
          <SmallInput value={t.title} onChange={(v) => update(i, "title", v)} placeholder="Track title" tokens={tokens} autoFocus={i === 0} />
          <SmallInput value={t.duration} onChange={(v) => update(i, "duration", v)} placeholder="3:42" tokens={tokens} />
        </div>
      ))}
      <AddBtn onClick={() => set("tracks", [...f.tracks, { number: f.tracks.length + 1, title: "", duration: "" }])} label="+ Add track" tokens={tokens} />
    </div>
  );
}

// ─── Link Group ───────────────────────────────────────────────────

function LinkGroup({
  fields, f, set, tokens,
}: {
  fields: { label: string; key: keyof FormData; placeholder: string }[];
  f: FormData; set: Setter; tokens: TokenSet;
}) {
  return (
    <div>
      {fields.map(({ label, key, placeholder }, i) => (
        <div key={key} style={{ marginBottom: "1rem" }}>
          <FieldLabel label={label} tokens={tokens} />
          <SmallInput
            value={f[key] as string}
            onChange={(v) => set(key, v)}
            placeholder={placeholder}
            tokens={tokens}
            autoFocus={i === 0}
          />
        </div>
      ))}
    </div>
  );
}

// ─── Contact Pair ─────────────────────────────────────────────────

function ContactPair({
  nameKey, nameLabel, emailKey, emailLabel, f, set, tokens,
}: {
  nameKey: keyof FormData; nameLabel: string;
  emailKey: keyof FormData; emailLabel: string;
  f: FormData; set: Setter; tokens: TokenSet;
}) {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.25rem" }}>
      <div>
        <FieldLabel label={nameLabel} tokens={tokens} />
        <SmallInput value={f[nameKey] as string} onChange={(v) => set(nameKey, v)} placeholder="Full name" tokens={tokens} autoFocus />
      </div>
      <div>
        <FieldLabel label={emailLabel} tokens={tokens} />
        <SmallInput value={f[emailKey] as string} onChange={(v) => set(emailKey, v)} placeholder="email@example.com" tokens={tokens} />
      </div>
    </div>
  );
}

// ─── Generate screen ──────────────────────────────────────────────

function GenerateScreen({ f, tokens }: { f: FormData; tokens: TokenSet }) {
  const [showContinue, setShowContinue] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setShowContinue(true), 2200);
    return () => clearTimeout(t);
  }, []);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "3rem" }}>
      <p style={{
        fontFamily: "'Inter', system-ui, sans-serif",
        fontSize: "clamp(0.9rem, 2.5vw, 1.1rem)",
        color: tokens.muted,
        lineHeight: 1.9,
        fontWeight: 300,
        letterSpacing: "0.01em",
        maxWidth: 420,
      }}>
        {f.contactName ? `${f.contactName}, ` : f.name ? `${f.name}, ` : ""}your world is taking shape.
        <br />
        we&apos;ll be in touch at {f.contactEmail || "your inbox"}.
      </p>
      <div style={{
        display: "inline-flex", alignItems: "center", gap: "1rem",
        padding: "1.25rem 1.75rem",
        background: "rgba(255,255,255,0.02)",
        border: `1px solid ${tokens.border}`,
        borderLeft: `3px solid ${tokens.accent}`,
        borderRadius: 8,
        maxWidth: 360,
      }}>
        <div style={{
          width: 8, height: 8, borderRadius: "50%",
          background: tokens.accent,
          flexShrink: 0,
          animation: "breathe 2.8s ease-in-out infinite",
        }} />
        <p style={{
          fontFamily: "'Inter', system-ui, sans-serif",
          fontSize: "0.82rem", color: tokens.muted2,
          letterSpacing: "0.04em", lineHeight: 1.6,
          fontWeight: 300,
        }}>
          {f.name || "your site"} · {f.genre || "your sound"}<br />
          building now.
        </p>
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem", opacity: showContinue ? 1 : 0, transition: "opacity 0.8s ease", pointerEvents: showContinue ? "auto" : "none" }}>
        <a
          href="/band/studio"
          style={{
            display: "inline-flex", alignItems: "center", gap: "0.6rem",
            fontFamily: "'Inter', system-ui, sans-serif",
            fontSize: "0.85rem", letterSpacing: "0.06em",
            color: tokens.accent, textDecoration: "none", fontWeight: 400,
          }}
        >
          see your site &nbsp;→
        </a>
        <a
          href="/band/build"
          style={{
            display: "inline-flex", alignItems: "center", gap: "0.6rem",
            fontFamily: "'Inter', system-ui, sans-serif",
            fontSize: "0.75rem", letterSpacing: "0.06em",
            color: "rgba(232,232,232,0.3)", textDecoration: "none", fontWeight: 300,
          }}
        >
          build your profile &nbsp;→
        </a>
      </div>
    </div>
  );
}

// ─── Question Definitions ─────────────────────────────────────────

interface Question {
  id: string;
  number?: number;
  question: (f: FormData) => string;
  hint?: (f: FormData) => string;
  optional?: boolean;
  canAdvance?: (f: FormData) => boolean;
  isGenre?: boolean;
  isGenerate?: boolean;
  isIntro?: boolean;
  render: (props: { f: FormData; set: Setter; tokens: TokenSet; onEnter: () => void }) => React.ReactNode;
}

const QUESTIONS: Question[] = [
  // 0 — Intro
  {
    id: "intro",
    isIntro: true,
    question: () => "in the beginning.",
    render: () => null,
  },
  // 1 — Artist/band name
  {
    id: "name",
    question: () => "introduce.",
    hint: () => "Your artist or band name.",
    canAdvance: (f) => f.name.trim().length > 0,
    render: ({ f, set, tokens, onEnter }) => (
      <QInput value={f.name} onChange={(v) => set("name", v)} placeholder="Artist or band name" tokens={tokens} onEnter={onEnter} />
    ),
  },
  // 2 — Email
  {
    id: "contactEmail",
    question: () => "reach.",
    hint: () => "Where we find you.",
    canAdvance: (f) => f.contactEmail.trim().includes("@"),
    render: ({ f, set, tokens, onEnter }) => (
      <QInput value={f.contactEmail} onChange={(v) => set("contactEmail", v)} placeholder="you@email.com" tokens={tokens} onEnter={onEnter} type="email" />
    ),
  },
  // 3 — Genre
  {
    id: "genre",
    isGenre: true,
    question: () => "vibe.",
    hint: () => "Choose your atmosphere.",
    canAdvance: (f) => f.genre.length > 0,
    render: ({ f, set, tokens }) => (
      <GenreSelector f={f} set={set} tokens={tokens} />
    ),
  },
  // 4 — Generate
  {
    id: "generate",
    isGenerate: true,
    question: (f) => f.name.trim() ? `${f.name}.` : "your world.",
    hint: () => "It begins.",
    render: ({ f, tokens }) => (
      <GenerateScreen f={f} tokens={tokens} />
    ),
  },
];

// ─── Main ─────────────────────────────────────────────────────────

const STORAGE_KEY = "bandstack-intake-v2";

export default function IntakeForm() {
  const [qIdx, setQIdx]       = useState(0);
  const [animKey, setAnimKey] = useState(0);
  const [exiting, setExiting] = useState(false);
  const [form, setForm]       = useState<FormData>(EMPTY);
  const [resumed, setResumed] = useState(false);

  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved) as FormData;
        if ("name" in parsed && parsed.name !== undefined) {
          setForm(parsed);
          setResumed(true);
        } else {
          localStorage.removeItem(STORAGE_KEY);
        }
      }
    } catch {}
  }, []);

  const set = useCallback((k: keyof FormData, v: unknown) => {
    setForm((prev) => {
      const next = { ...prev, [k]: v };
      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); } catch {}
      return next;
    });
  }, []);

  const tokens = form.genre
    ? resolveTokens([form.genre])
    : DEFAULT_TOKENS;

  const q = QUESTIONS[qIdx];
  const total = QUESTIONS.length;
  const progress = (qIdx + 1) / total;

  const canAdvance = q.canAdvance ? q.canAdvance(form) : true;

  const advance = useCallback(() => {
    if (qIdx < total - 1) {
      setExiting(true);
      setTimeout(() => {
        setExiting(false);
        setAnimKey((k) => k + 1);
        setQIdx((i) => i + 1);
      }, 320);
    }
  }, [qIdx, total]);

  const back = () => {
    if (qIdx > 0) {
      setExiting(true);
      setTimeout(() => {
        setExiting(false);
        setAnimKey((k) => k + 1);
        setQIdx((i) => i - 1);
      }, 320);
    }
  };

  // Enter to advance — only from non-input/textarea contexts (inputs handle their own)
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName;
      if (tag === "INPUT" || tag === "TEXTAREA" || tag === "SELECT") return;
      if (e.key === "Enter" && canAdvance && !q.isGenerate) {
        e.preventDefault();
        advance();
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [advance, canAdvance, q.isGenerate]);

  // Glow tint — genre accent at very low opacity
  const glowHex = tokens.accent;

  return (
    <main style={{ minHeight: "100vh", background: tokens.bg, position: "relative", overflow: "hidden", transition: "background 0.6s ease" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,600&display=swap');
        @keyframes slideInLeft {
          from { opacity: 0; transform: translateX(-52px); }
          to   { opacity: 1; transform: translateX(0); }
        }
        @keyframes slideOutLeft {
          from { opacity: 1; transform: translateX(0); }
          to   { opacity: 0; transform: translateX(-52px); }
        }
        .q-enter { animation: slideInLeft 0.42s cubic-bezier(0.16, 1, 0.3, 1) forwards; }
        .q-exit  { animation: slideOutLeft 0.28s cubic-bezier(0.4, 0, 1, 1) forwards; pointer-events: none; }
        @keyframes fadeIn {
          from { opacity: 0; }
          to   { opacity: 1; }
        }
        @keyframes breathe {
          0%, 100% { transform: scale(1); opacity: 0.35; }
          50%      { transform: scale(1.55); opacity: 1; }
        }
        @keyframes ripple {
          0%   { transform: scale(1); opacity: 0.7; }
          100% { transform: scale(4); opacity: 0; }
        }
        .pulse-dot { animation: breathe 2.8s ease-in-out infinite; }
        .pulse-dot:hover { animation: none; opacity: 1 !important; transform: scale(1.2); }
        .pulse-dot.fired::after {
          content: '';
          position: absolute; inset: 0; border-radius: 50%;
          background: currentColor;
          animation: ripple 0.5s ease-out forwards;
        }
        ::placeholder { color: rgba(232,232,232,0.3) !important; }
      `}</style>

      {/* Background glow — shifts with genre */}
      <div
        aria-hidden
        style={{
          position: "fixed", inset: 0, zIndex: 0, pointerEvents: "none",
          background: `radial-gradient(ellipse 65% 45% at 50% 38%, ${glowHex}18 0%, transparent 70%)`,
          transition: "background 0.8s ease",
        }}
      />

      {/* Progress bar */}
      <div style={{ position: "fixed", top: 0, left: 0, right: 0, height: 2, background: "rgba(255,255,255,0.05)", zIndex: 100 }}>
        <div style={{
          height: "100%",
          width: `${progress * 100}%`,
          background: glowHex,
          transition: "width 0.5s ease, background 0.6s ease",
        }} />
      </div>

      {/* Back button */}
      {qIdx > 0 && (
        <button
          type="button"
          onClick={back}
          style={{
            position: "fixed", top: 20, left: 28, zIndex: 50,
            background: "transparent", border: "none",
            color: tokens.muted2, fontSize: "1rem",
            cursor: "pointer", padding: "8px 12px",
            fontFamily: "'Inter', system-ui, sans-serif",
            transition: "color 0.2s ease",
          }}
          onMouseEnter={(e) => { (e.currentTarget as HTMLButtonElement).style.color = tokens.muted; }}
          onMouseLeave={(e) => { (e.currentTarget as HTMLButtonElement).style.color = tokens.muted2; }}
        >
          ← Back
        </button>
      )}

      {/* Question counter — hidden on intro */}
      {!q.isIntro && (
        <div style={{ position: "fixed", top: 28, right: 28, zIndex: 50 }}>
          <span style={{ fontFamily: "monospace", fontSize: "0.72rem", color: tokens.muted }}>
            {qIdx}
          </span>
          <span style={{ fontFamily: "monospace", fontSize: "0.72rem", color: tokens.muted2 }}>
            &nbsp;/ 3
          </span>
        </div>
      )}

      {/* Intro screen */}
      <div
        onClick={advance}
        style={{
          position: "fixed", inset: 0, zIndex: 1,
          display: q.isIntro ? "flex" : "none",
          flexDirection: "column",
          alignItems: "flex-start", justifyContent: "center",
          padding: "0 28px",
          cursor: "default",
        }}
      >
        <div
          key={`intro-${animKey}`}
          className={exiting ? "q-exit" : "q-enter"}
          style={{ maxWidth: 580 }}
        >
          <h1 style={{
            fontFamily: "'Cormorant Garamond', Georgia, serif",
            fontStyle: "italic", fontWeight: 600,
            fontSize: "clamp(4rem, 18vw, 9rem)",
            lineHeight: 1.0, color: "#e8e8e8",
            letterSpacing: "-0.01em", marginBottom: "2.5rem",
            animation: "fadeIn 1.8s ease forwards",
          }}>
            {resumed ? "welcome back." : "in the beginning."}
          </h1>
          <p style={{
            fontFamily: "'Inter', system-ui, sans-serif",
            fontSize: "clamp(0.85rem, 2vw, 1rem)",
            color: "rgba(232,232,232,0.28)", fontWeight: 300,
            letterSpacing: "0.06em", lineHeight: 1.8,
            animation: "fadeIn 3.2s ease forwards",
          }}>
            {resumed ? "pick up where you left off." : "you create your own experience."}
          </p>
          <div style={{ marginTop: "5rem" }}>
            <div className="pulse-dot" style={{
              width: 12, height: 12, borderRadius: "50%",
              background: "rgba(232,232,232,0.4)",
              color: "rgba(232,232,232,0.4)", position: "relative",
            }} />
          </div>
        </div>
      </div>

      {/* Question area */}
      <div style={{
        minHeight: "100vh", display: q.isIntro ? "none" : "flex",
        alignItems: "center", justifyContent: "center",
        padding: "80px 28px", position: "relative", zIndex: 1,
      }}>
        <div
          key={animKey}
          className={exiting ? "q-exit" : "q-enter"}
          style={{ width: "100%", maxWidth: 580 }}
        >

          {/* Optional badge */}
          {q.optional && (
            <span style={{
              display: "inline-block",
              fontFamily: "monospace", fontSize: "0.55rem", letterSpacing: "0.18em",
              textTransform: "uppercase", color: tokens.muted2,
              border: `1px solid ${tokens.border2}`, borderRadius: "9999px",
              padding: "3px 10px", marginBottom: "1.25rem",
            }}>
              Optional
            </span>
          )}

          {/* Question */}
          <h1 style={{
            fontFamily: "'Cormorant Garamond', Georgia, serif",
            fontStyle: "italic",
            fontWeight: 600,
            fontSize: "clamp(3.2rem, 14vw, 7rem)",
            lineHeight: 1.0, color: tokens.text,
            letterSpacing: "-0.01em",
            marginBottom: "1.75rem",
          }}>
            {q.question(form)}
          </h1>

          {/* Hint */}
          {q.hint && (
            <p style={{
              fontFamily: "'Inter', system-ui, sans-serif",
              fontSize: "clamp(0.85rem, 2vw, 0.95rem)",
              color: tokens.muted2, lineHeight: 1.7,
              marginBottom: "3.5rem",
              fontWeight: 300,
              letterSpacing: "0.01em",
            }}>
              {q.hint(form)}
            </p>
          )}

          {/* Field */}
          {q.render({ f: form, set, tokens, onEnter: advance })}

          {/* Actions — dot always shows; dim+slow when empty, bright when filled */}
          {!q.isGenerate && (
            <div style={{ marginTop: "4rem", display: "flex", alignItems: "center", gap: "2.5rem" }}>
              <button
                type="button"
                onClick={advance}
                style={{
                  position: "relative",
                  width: 14, height: 14,
                  borderRadius: "50%",
                  background: canAdvance ? tokens.accent : "rgba(232,232,232,0.25)",
                  border: "none",
                  cursor: "pointer",
                  padding: 0,
                  flexShrink: 0,
                  animation: canAdvance
                    ? "breathe 2.8s ease-in-out infinite"
                    : "breathe 5s ease-in-out infinite",
                  opacity: canAdvance ? 1 : 0.45,
                  transition: "background 0.4s ease, opacity 0.4s ease",
                }}
                aria-label="continue"
              />
            </div>
          )}

        </div>
      </div>

    </main>
  );
}
